# Generated by Django 5.0 on 2024-01-03 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_specialists', models.CharField(max_length=100)),
                ('doctor_code', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'Doctor_Specialists',
                'ordering': ['-doctor_specialists'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_surname', models.CharField(max_length=100)),
                ('doctor_img', models.FileField(blank=True, null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('specialists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Doctors.specialist')),
            ],
            options={
                'db_table': 'doctor_list',
                'ordering': ['-doctor_name'],
            },
        ),
    ]
