# Generated by Django 5.0 on 2024-01-09 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_Doctors', '0001_initial'),
        ('app_Patients', '0002_alter_patient_patient_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Patients.patient')),
            ],
            options={
                'db_table': 'Appointments',
                'ordering': ['-appointment_date'],
            },
        ),
    ]
